Grid:
  SizeX: "160"
  SizeY: "160"

Agent:
  Max: "1000"

Neuron:
  Max: "128"

Genome:
  Max: "128"
  Min: "128"

Activation:
  Threshold: "0.85"

MateTopNPercent:
  TopN: "0.3"

MinDominantCutPercent:
  Min: "0.6"

DistanceWeight:
  Weight: "0.8"

StepsTakenWeight:
  Weight: "0.2"